apiVersion: 1

datasources:
  - name: InfluxDB - Sensor Data
    type: influxdb
    access: proxy
    uid: influxdb-sensors
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: smart-building
      defaultBucket: sensor_data
      tlsSkipVerify: true
    secureJsonData:
      token: smart-building-token-2026
    editable: true
    isDefault: true

  - name: InfluxDB - eKuiper Monitoring
    type: influxdb
    access: proxy
    uid: influxdb-ekuiper
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: smart-building
      defaultBucket: monitoring_ekuiper
      tlsSkipVerify: true
    secureJsonData:
      token: smart-building-token-2026
    editable: true
    isDefault: false

  - name: InfluxDB - NanoMQ Monitoring
    type: influxdb
    access: proxy
    uid: influxdb-nanomq
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: smart-building
      defaultBucket: monitoring_nanomq
      tlsSkipVerify: true
    secureJsonData:
      token: smart-building-token-2026
    editable: true
    isDefault: false
